name: "Terraform-Plan-Infra-Plan"

on:
  push:
    branches:
      - FeatureBranch1

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.MYSUPERSECRETE}}
      ARM_SUBSCRIPTION_ID: ${{secrets.MYSBSCRIPTIONID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color